### ISSUE TITLE
Pie is white when some pies have small numbers compared to other pies

### ISSUE THREAD

**Issue by SenBal** [arekgofi/svg-charts#2]
this function svgc.generatePieChartSVG(values,colors,radius,strokeSize,strokeColor), doesn't work and shows a white background when the values are a mix of very large number and at least 1 very small number (e.g. values = [1, 1222, 2], values = [1,1,65010])

**Comment by lord5et** [comment]
I see no point in showing such big number with two such small numbers on one chart.
I used [chartjs](https://www.chartjs.org/) library and it behaves exactly the same as mine for your input.
Closing
